In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from collections import namedtuple
from toolz import first
import numpy as np
from nbc_analysis.utils.debug_utils import runit
from nbc_analysis.utils.config_utils import get_config
from pathlib import Path

from test_create_days import test_create_days
#from nbc_analysis.utils.date_utils import ds_dt2uts_ms, ds_uts_ms2dt, dt2uts_ms, uts_ms2dt

In [5]:

df = runit(test_create_days)

>> Using default config
>> creating days calendar,start_day_key=20170101,end_day_key=20210101
>> wrote file,outfile=/Users/wmcabee/DATA/NBC/calendar/cal_days.parquet,records=1461

In [6]:
config = get_config(config='default')
calendar_d = Path(config['CALENDAR_D'])

>> Using default config

In [7]:
infile = first(calendar_d.glob('*'))

df = pd.read_parquet(infile)
df.T

,0,1,2,3,4,5,6,7,8,9,...,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460
day_key,20170101,20170102,20170103,20170104,20170105,20170106,20170107,20170108,20170109,20170110,...,20201222,20201223,20201224,20201225,20201226,20201227,20201228,20201229,20201230,20201231
ordinal,17167,17168,17169,17170,17171,17172,17173,17174,17175,17176,...,18618,18619,18620,18621,18622,18623,18624,18625,18626,18627
day,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
month,1,1,1,1,1,1,1,1,1,1,...,12,12,12,12,12,12,12,12,12,12
year,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
dayofweek,6,0,1,2,3,4,5,6,0,1,...,1,2,3,4,5,6,0,1,2,3
day_name,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,...,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday
month_name,January,January,January,January,January,January,January,January,January,January,...,December,December,December,December,December,December,December,December,December,December
days_in_month,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
quarter,1,1,1,1,1,1,1,1,1,1,...,4,4,4,4,4,4,4,4,4,4
dayofyear,1,2,3,4,5,6,7,8,9,10,...,357,358,359,360,361,362,363,364,365,366
week,52,1,1,1,1,1,1,1,2,2,...,52,52,52,52,52,52,53,53,53,53
weekday,6,0,1,2,3,4,5,6,0,1,...,1,2,3,4,5,6,0,1,2,3
weekofyear,52,1,1,1,1,1,1,1,2,2,...,52,52,52,52,52,52,53,53,53,53
week_id,2017W52,2017W01,2017W01,2017W01,2017W01,2017W01,2017W01,2017W01,2017W02,2017W02,...,2020W52,2020W52,2020W52,2020W52,2020W52,2020W52,2020W53,2020W53,2020W53,2020W53
is_leap_year,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
is_week_start,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
is_week_end,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
is_month_start,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
is_month_end,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
is_quarter_start,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
is_quarter_end,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
is_year_start,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
is_year_end,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
start_time,2017-01-01T00:00:00,2017-01-02T00:00:00,2017-01-03T00:00:00,2017-01-04T00:00:00,2017-01-05T00:00:00,2017-01-06T00:00:00,2017-01-07T00:00:00,2017-01-08T00:00:00,2017-01-09T00:00:00,2017-01-10T00:00:00,...,2020-12-22T00:00:00,2020-12-23T00:00:00,2020-12-24T00:00:00,2020-12-25T00:00:00,2020-12-26T00:00:00,2020-12-27T00:00:00,2020-12-28T00:00:00,2020-12-29T00:00:00,2020-12-30T00:00:00,2020-12-31T00:00:00
end_time,2017-01-02T00:00:00,2017-01-03T00:00:00,2017-01-04T00:00:00,2017-01-05T00:00:00,2017-01-06T00:00:00,2017-01-07T00:00:00,2017-01-08T00:00:00,2017-01-09T00:00:00,2017-01-10T00:00:00,2017-01-11T00:00:00,...,2020-12-23T00:00:00,2020-12-24T00:00:00,2020-12-25T00:00:00,2020-12-26T00:00:00,2020-12-27T00:00:00,2020-12-28T00:00:00,2020-12-29T00:00:00,2020-12-30T00:00:00,2020-12-31T00:00:00,2021-01-01T00:00:00
start_uts_ms,1483228800000,1483315200000,1483401600000,1483488000000,1483574400000,1483660800000,1483747200000,1483833600000,1483920000000,1484006400000,...,1608595200000,1608681600000,1608768000000,1608854400000,1608940800000,1609027200000,1609113600000,1609200000000,1609286400000,1609372800000
end_uts_ms,1483315200000,1483401600000,1483488000000,1483574400000,1483660800000,1483747200000,1483833600000,1483920000000,1484006400000,1484092800000,...,1608681600000,1608768000000,1608854400000,1608940800000,1609027200000,1609113600000,1609200000000,1609286400000,1609372800000,1609459200000